# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _clubgen_c
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class intArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _clubgen_c.new_intArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _clubgen_c.delete_intArray
    __del__ = lambda self : None;
    def __getitem__(*args): return _clubgen_c.intArray___getitem__(*args)
    def __setitem__(*args): return _clubgen_c.intArray___setitem__(*args)
    def cast(*args): return _clubgen_c.intArray_cast(*args)
    __swig_getmethods__["frompointer"] = lambda x: _clubgen_c.intArray_frompointer
    if _newclass:frompointer = staticmethod(_clubgen_c.intArray_frompointer)
intArray_swigregister = _clubgen_c.intArray_swigregister
intArray_swigregister(intArray)
intArray_frompointer = _clubgen_c.intArray_frompointer

GenAlignment_c = _clubgen_c.GenAlignment_c
LocalFilter = _clubgen_c.LocalFilter
TesterAlign_c = _clubgen_c.TesterAlign_c
int_array = _clubgen_c.int_array
int_array_1000 = _clubgen_c.int_array_1000
a_set = _clubgen_c.a_set
a_get = _clubgen_c.a_get
min = _clubgen_c.min
max = _clubgen_c.max


